services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Your_password123"
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ASPNETCORE_URLS: http://+:8080
      ConnectionStrings__DefaultConnection: Server=db;Database=Predictorator;User Id=sa;Password=Your_password123;Encrypt=False
      ADMIN_EMAIL: admin@example.com
      ADMIN_PASSWORD: Admin123!
      DataProtection__KeyPath: /var/dp-keys
    depends_on:
      - db
    ports:
      - "8080:8080"
    volumes:
      - dp-keys:/var/dp-keys

volumes:
  mssql-data:
  dp-keys:
