name: CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - name: Build
        run: dotnet build Predictorator.sln --configuration Release
      - name: Publish
        run: dotnet publish Predictorator.sln -c Release -o publish
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: publish

  deploy_staging:
    runs-on: ubuntu-latest
    needs: build
    environment: staging
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to staging
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'predictorator5000'
          slot-name: 'staging'
          package: ./

  tests:
    runs-on: ubuntu-latest
    needs: deploy_staging
    env:
      RUN_UI_TESTS: 'true'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - name: Install Playwright browsers
        run: |
          dotnet tool install --global Microsoft.Playwright.CLI
          export PATH="$PATH:/root/.dotnet/tools"
          playwright install --with-deps
      - name: Run all tests
        run: dotnet test Predictorator.sln --logger trx -- RunConfiguration.TestRunParameters.Parameter(name=BaseUrl,value=${{ vars.STAGING_URL }})

  deploy_prod:
    runs-on: ubuntu-latest
    needs: tests
    environment: production
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: app
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Deploy to production
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'predictorator5000'
          slot-name: 'Production'
          package: ./

