name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    if: github.actor == github.repository_owner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          global-json-file: global.json
          include-prerelease: true
      - name: Restore
        run: dotnet restore Predictorator.sln
      - name: Run unit tests
        run: dotnet test Predictorator.sln
