name: PR Validation

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'
      - name: Restore
        run: dotnet restore Predictorator.sln
      - name: Run unit tests
        run: dotnet test Predictorator.sln --no-build
